from fastapi import Depends, HTTPException, APIRouter, Form
from ..auth.route import authenticate
from .query import research_paper_summary
from ..config.db import research_paper_collection, summary_collection
import time

router = APIRouter(prefix="/summary", tags=["summary"])


@router.post("/from_summary")
async def summary(user=Depends(authenticate), doc_id: str = Form(...), query: str = Form(default="Please summarize and critique this research paper")):
    paper = research_paper_collection.find_one({"doc_id": doc_id})
    if not paper:
        raise HTTPException(status_code=404, detail="Research paper not found")
    
    #ensure only a uploader can sumamrize the paper
    if paper["uploader"] != user["username"]:
        raise HTTPException(status_code=406, detail="You cannot access another user's paper")
    
    #call rag pipeline
    res = await research_paper_summary(user["username"], doc_id, query)
    
    # persist the summary in mongo
    summary_collection.insert_one({
        "doc_id": doc_id,
        "requester": user["username"],
        "question": query,
        "response": res.get("summary"),
        "sources": res.get("sources", []),
        "timestamp": time.time()
    })
    
    return res

@router.get("/by_user")
async def get_user_summaries(user=Depends(authenticate)):
    # fetch all summaries generated by this user
    summaries = summary_collection.find({"requester": user["username"]})
    if not summaries: 
        raise HTTPException(status_code=404, detail="No summary found for this user")
    
    records_list = []
    for record in summaries:
        record["_id"] = str(record["_id"])
        records_list.append(record)
    
    return records_list
    
    